// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products_and_Categories.Models;

#nullable disable

namespace Products_and_Categories.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240216111437_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Products_and_Categories.Models.Assossiations", b =>
                {
                    b.Property<int>("AssossiationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriesCategorieId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("AssossiationId");

                    b.HasIndex("CategoriesCategorieId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("Assossiations");
                });

            modelBuilder.Entity("Products_and_Categories.Models.Categories", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategorieId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Products_and_Categories.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Products_and_Categories.Models.Assossiations", b =>
                {
                    b.HasOne("Products_and_Categories.Models.Categories", "Categories")
                        .WithMany("Cat")
                        .HasForeignKey("CategoriesCategorieId");

                    b.HasOne("Products_and_Categories.Models.Products", "Products")
                        .WithMany("Prod")
                        .HasForeignKey("ProductsProductId");

                    b.Navigation("Categories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Products_and_Categories.Models.Categories", b =>
                {
                    b.Navigation("Cat");
                });

            modelBuilder.Entity("Products_and_Categories.Models.Products", b =>
                {
                    b.Navigation("Prod");
                });
#pragma warning restore 612, 618
        }
    }
}
